/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface openai {
  content: string;
  model?: string;
  prompt: string;
  temperature?: number;
  variables?: any;
}
