/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface appendVariable {
  name: string;
  variable: string;
}

export interface createPrompt {
  name: string;
  text: string;
  variables?: string[];
}

export interface deletePrompt {
  name: string;
}

export interface getPrompt {
  name?: string;
}

export interface removeVariable {
  name: string;
  variable: string;
}

export interface updatePrompt {
  name: string;
  prompt?: {
    name?: string;
    text?: string;
  };
}
